apiVersion: v1
kind: Service
metadata:
  name: nodeport-api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vollmed
  ports:
    - port: 3000     
      targetPort: 3000     
      nodePort: 30007